### PR TITLE
BUGFIX: `vcd_vapp_vm` `network` update causes existing NICs to change MAC addresses

### LINKED ISSUE #407: vcd_vapp_vm: Adding a secondary network interface also changes the first interface
### Terraform Version
Terraform v0.12.15
terraform-provider-vcd_v2.5.0_x4

### Affected Resource(s)
vcd_vapp_vm

### Terraform Configuration Files
```hcl
resource "vcd_vapp_vm" "instance" {
  name          = var.hostname
  computer_name = var.hostname
  vapp_name     = vcd_vapp.vapp.name
  catalog_name  = var.image_catalog
  template_name = var.image_string
  cpus          = var.cpu
  cpu_cores     = var.core
  memory        = var.ram

  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = "POOL"
    is_primary         = true
  }
}
```

### Expected Behavior
If we add a new `network` block, terraform should attach a new interface to the vm. The current first interface should not be changed.

### Actual Behavior
If we add a new `network` block, terraform also redeploys the first interface. It gets a new IP address and also a new MAC address.

### Steps to Reproduce
Roll out the configuration above.

Look into terraform.tfstate:
```hcl
[...]
            "network": [
              {
                "ip": "10.70.21.8",
                "ip_allocation_mode": "POOL",
                "is_primary": true,
                "mac": "00:50:56:0b:02:5f",
                "name": "XXX",
                "type": "org"
              }
            ],
[...]
```
Add the following to the configuration in the `vcd_vapp_vm` resource:
```hcl
  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = "POOL"
  }
```
Run `terraform apply` (it says that it only will add a new interface):
```hcl
[...]
        network {
            ip                 = "10.70.21.8"
            ip_allocation_mode = "POOL"
            is_primary         = true
            mac                = "00:50:56:0b:02:5f"
            name               = "XXX"
            type               = "org"
        }
      + network {
          + ip_allocation_mode = "POOL"
          + name               = "XXX"
          + type               = "org"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
Look into the terraform.tfstate:
```hcl
[...]
            "network": [
              {
                "ip": "10.70.21.9",
                "ip_allocation_mode": "POOL",
                "is_primary": true,
                "mac": "00:50:56:0b:02:60",
                "name": "XXX",
                "type": "org"
              },
              {
                "ip": "10.70.21.10",
                "ip_allocation_mode": "POOL",
                "is_primary": false,
                "mac": "00:50:56:0b:02:61",
                "name": "XXX",
                "type": "org"
              }
            ],
[...]
```
Also the IP and MAC of the first interface have changed.

### PR DESCRIPTION
**Pull request by Didainius**
Fixes #407
This PR should fix a bug where MAC address was not sent to API during an update procedure. As a result MAC addresses would change during an update and this caused IP address change and other problems.

Commit b8a01d5 introduced a failing test to validate such situation while fe713c4 added a fix.

Note. Test suites passed on 9.5 and 10.

### CODE REVIEW

File: vcd/helpers_test.go [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+
+package vcd
+
+import (
+	"fmt"
+
+	"github.com/hashicorp/terraform-plugin-sdk/helper/resource"
+	"github.com/hashicorp/terraform-plugin-sdk/terraform"
+)
+
```
Comment (lvirbalas) [inline vcd/helpers_test.go]: Personally, I would like to see a general comment about this new file, so its purpose is clear and we know what functions to put here in the future.

File: CHANGELOG.md [hunk 2]
```diff
@@ -3,19 +3,26 @@
...
 
-BUG FIXES:
-Fix `vcd_vapp_vm` resource read - independent disks where losing `bus_number` and `unit_number` values after refresh. [#433]
+BUG FIXES: Fix `vcd_vapp_vm` resource read - independent disks where losing `bus_number` and
+`unit_number` values after refresh. [GH-433]
 
 NOTES:
 * Drop support for vCD 9.0
 
+BUG FIXES:
```
Comment (vbauzysvmware) [inline CHANGELOG.md]: BUG FIXES are added two times

File: vcd/helpers_test.go (hunk 1 above)
Comment (Didainius) [reply vcd/helpers_test.go]: On a second thought maybe I should name the file as `testcheck_funcs_test.go` as this is what it currently contains. Some custom functions which have `TestCheckFunc`signature and are suitable to use together with Terraform built-in `resource.TestCheck...` functions.

File: vcd/helpers_test.go [hunk 3]
```diff
@@ -0,0 +1,63 @@
+// +build vapp vm ALL functional
```
Comment (vbauzysvmware) [inline vcd/helpers_test.go]: proposal: helpers_test.go -> custom_terraform_assertions_test.go

File: vcd/helpers_test.go [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+// to check whether MAC address does not change when a `vcd_vapp_vm` resource's network stack is
+// updated (between different TestSteps).
+type testCachedFieldValue struct {
+	fieldValue string
+}
+
+// testCacheResourceFieldValue has the same signature as builtin Terraform Test functions, however
+// it is attached to a struct which allows to store a field value and then check against this value
+// with 'testCheckCachedResourceFieldValue'
+func (c *testCachedFieldValue) testCacheResourceFieldValue(resource, field string) resource.TestCheckFunc {
```
Comment (vbauzysvmware) [inline vcd/helpers_test.go]:
```suggestion
func (c *testCachedFieldValue) cacheTestResourceFieldValue(resource, field string) resource.TestCheckFunc {
```

File: vcd/helpers_test.go (hunk 3 above)
Comment (Didainius) [reply vcd/helpers_test.go]: Ok, casting a vote here:
* testcheck_funcs_test.go
* custom_terraform_assertions_test.go

cc @lvirbalas @dataclouder

File: CHANGELOG.md [hunk 5]
```diff
@@ -3,19 +3,26 @@
 FEATURES:
 
 * **New Resource:** `vcd_vm_internal_disk` VM internal disk configuration
```
Comment (Didainius) [inline CHANGELOG.md]:
```suggestion
* **New Resource:** `vcd_vm_internal_disk` VM internal disk configuration [GH-412]
```

File: vcd/helpers_test.go (hunk 3 above)
Comment (vbauzysvmware) [reply vcd/helpers_test.go]: I am ok with both ;-)

Comment (lvirbalas) [reply vcd/helpers_test.go]: Maybe a third variant:
* custom_assertions_test.go

p.s. Just noticed a typo in comment:
`accross -> across`

File: vcd/helpers_test.go (hunk 4 above)
Comment (Didainius) [reply vcd/helpers_test.go]: Makes sense. Changed.

File: vcd/helpers_test.go (hunk 3 above)
Comment (Didainius) [reply vcd/helpers_test.go]: > p.s. Just noticed a typo in comment:
> `accross -> across`

Thanks. Fixed.

File: CHANGELOG.md (hunk 2 above)
Comment (Didainius) [reply CHANGELOG.md]: Fixed.

**Comment by NilsBusche** [comment]
I have tested the fix. Already existing network interfaces are not changed anymore. LGTM!

**Comment by alxgu** [comment]
Can this PR be merged?
Could you please give me a status update? Thanks for your help.

**Comment by Didainius** [comment]
> Can this PR be merged?
> Could you please give me a status update? Thanks for your help.

@alxgu, this will probably be merged however two more review approvals are pending. If they don't detect any problem and are happy with code quality - it will be merged.

File: vcd/helpers_test.go (hunk 3 above)
Comment (lvirbalas) [reply vcd/helpers_test.go]: After further discussion, OK with `testcheck_funcs_test.go`, because:
1. It has custom TestCheckFunc inside
2. It is consistent with `suppress_funcs.go` and `validate_funcs.go`
